---
driver:
  name: digitalocean
driver_config:
  ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

provisioner:
  name: chef_solo

platforms:
  - name: centos-6-5-x64
  - name: ubuntu-12-04-x64

suites:
  - name: default
    run_list:
      - recipe[opt-git::default]
    attributes: {}
